config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'bars#index'

  resources :bars
  resources :verified, only: [:index]
  resources :free, only: [:index]
  resources :days, only: [:index, :show], param: :name

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bar.rb
class Bar < ApplicationRecord
  validates :name, presence: true
  validates :day, presence: true, inclusion: { in: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']}
  validates :time, presence: true
  validates :address, presence: true
  validates :website, presence: true
  validates :details, presence: true

end

app/models/day.rb
class Day < ApplicationRecord
  validates :name, presence: true

  has_many :bars

  def to_param
    name
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bars_controller.rb
class BarsController < ApplicationController
  def index
    @bars = Bar.all.order(name: :asc)
  end

  def show
    @bar = Bar.find(params[:id])
  end

  def new
  
    @bar = Bar.new
  end

  def create
    @bar = Bar.new(bar_params)
    if @bar.save
      flash[:notice] = "Bar Listing created!"
      redirect_to bars_path
    else
      flash.now[:notice] = "Bar Listing not created. Please fill out all sections."
      render :new
    end
  end

  private

  def bar_params
    params.require(:bar).permit(
      :name,
      :details,
      :day,
      :time,
      :cover_charge,
      :website,
      :address
    )
  end
end

app/controllers/days_controller.rb
class DaysController < ApplicationController
  def index
    @days = Day.all
  end

  def show
    @day = Day.find_by(name: params[:name])
    @bars = Bar.where(day: @day.name)
  end

end

app/controllers/free_controller.rb
class FreeController < ApplicationController
  def index
    @bars = Bar.where(cover_charge: :false).order(name: :asc)
  end
end

app/controllers/verified_controller.rb
class VerifiedController < ApplicationController

  def index
    @bars = Bar.where(verified: :true)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bars/_form.html.erb
<%= form_for @bar do |f| %>

  <div class="field">
    <%= f.label :name, "Name" %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :address, "Address" %>
    <%= f.text_field :address %>
  </div>

  <div class="field">
    <%= f.label :day, "Weekday" %>
    <%= f.select :day, options_for_select(['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']) %>
  </div>

  <div class="field">
    <%= f.label :time, "Time" %>
    <%= f.text_field :time %>
  </div>

  <div class="field">
    <%= f.label :website, "Website" %>
    <%= f.text_field :website %>
  </div>

  <div class="field">
    <%= f.label :details, "Details" %>
    <%= f.text_area :details %>
  </div>

  <div class="field">
    <%= f.label :cover_charge, "Cover Charge?" %>
    <%= f.check_box :cover_charge %>
  </div>

  <div class="actions">
    <%= f.submit value='Submit' %>
  </div>
<% end %>

app/views/bars/index.html.erb
<div>
  <div id='title'>Karaoke Boston</div>

  <div id='details'>
    <p>
      Looking for some karaoke in the Boston area? You've come to the right place!
    </p>
  </div>

  <div id = 'bars'>
    <% @bars.each do |bar| %>
      <p>
        <%= link_to bar.name, bar %> - <%= bar.day %> - <%= bar.time %><br/>
        Verified: <%= bar.verified %> // Cover Charge: <%= bar.cover_charge %>
      </p>
    <% end %>
  </div>
</div>

app/views/bars/new.html.erb
<div id='create'>Create New Karaoke Bar Listing:</div>

<%= render 'form', bars: @bars %>

<%= link_to 'Cancel', bars_path %>

app/views/bars/show.html.erb
<div>
  <div id='title'>
    <%= @bar.name %>
  </div>

  <p><%= @bar.details %></p>
  <p>When: <%= @bar.day %> @ <%= @bar.time %></p>
  <p>Address: <%= @bar.address %></p>
  <p>Website: <a href='<%=@bar.website%>'><%= @bar.website %></a></p>
  <p>Cover charge? <%= @bar.cover_charge %></p>
  <p>Verified? <%= @bar.verified %></p>
</div>

app/views/days/index.html.erb
<div id='title' class='text-center'>
  Karaoke Bars by Weekday:
</div>

<div class='text-center' id='days'>
  <% @days.each do |day| %>
    <p><%= link_to day.name, day %></p>
  <% end %>
</div>

app/views/days/show.html.erb
<div id='title'><%= @day.name %> Karaoke</div>

<% @bars.each do |bar| %>
  <p>
    <%= link_to bar.name, bar %> - <%= bar.day %> - <%= bar.time %><br/>
    Verified: <%= bar.verified %> // Cover Charge: <%= bar.cover_charge %>
  </p>
<% end %>

app/views/free/index.html.erb
<div id='title'>
  Free Karaoke Bars
</div>

<% @bars.each do |bar| %>
  <p>
    <%= link_to bar.name, bar %> - <%= bar.day %> - <%= bar.time %><br/>
    Verified: <%= bar.verified %> // Cover Charge: <%= bar.cover_charge %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Karaoke Boston" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <div id='body'>
    <body>
      <% if notice %>
        <div id="flash" class='small-9 small-offset-3 columns'>
          <div id="container">
              <div class="alert alert-success"><%= notice %></div>
          </div>
        </div>
      <% end %>
      <% if alert %>
        <div id="flash" class='small-9 small-offset-3 columns'>
          <div id="container">
            <div class="alert alert-danger"><%= alert %></div>
          </div>
        </div>
      <% end %>

      <div class="side-nav small-3 columns" id='sidebar'>
        <p>
        <% if user_signed_in? %>
          Logged in as <strong><%= current_user.email %></strong>.<br/>
          <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
          <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
        <% else %>
          <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
          <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
        <% end %>
        </p>
        <p><%= link_to 'All Karaoke Bars', bars_path %></p>
        <p><%= link_to 'Karaoke Bars By Weekday', days_path %></p>
        <p><%= link_to 'Free/No Cover Charge Karaoke Bars', free_index_path %></p>
        <p><%= link_to 'Verified Karaoke Bars Only', verified_index_path %></p>
        <p><%= link_to 'Create New Karaoke Bar Listing', new_bar_path %></p>
      </div>

      <div id='main' class='small-9 small-offset-3 columns float-left'>
        <%= yield %>
      </div>

    </body>
  </div>
</html>

app/views/sunday/index.html.erb
<div id='title'>Sunday Karaoke</div>

<% @bars.each do |bar| %>
  <p>
    <%= link_to bar.name, bar %> - <%= bar.day %> - <%= bar.time %><br/>
    Verified: <%= bar.verified %> // Cover Charge: <%= bar.cover_charge %>
  </p>
<% end %>

app/views/verified/index.html.erb
<div id='title'>
  Verified Karaoke Bars
</div>

<% @bars.each do |bar| %>
  <p>
    <%= link_to bar.name, bar %> - <%= bar.day %> - <%= bar.time %><br/>
    Verified: <%= bar.verified %> // Cover Charge: <%= bar.cover_charge %>
  </p>
<% end %>